name: release

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  check-branch:
    if: startsWith(github.head_ref, 'release-v')
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo run release on branch=${{ github.head_ref }}
  lint:
    needs: [check-branch]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo make lint

  test:
    needs: [check-branch]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo make test

  release:
    if: startsWith(github.head_ref, 'release-v')
    needs: [lint, test]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - run: |
          echo ${{ github.head_ref }}
      - uses: actions/checkout@v3
      - name: create release.zip
        run: |
          utils/release.sh
      - uses: softprops/action-gh-release@v1
        with:
          name:  ${{ github.event.pull_request.title }}
          tag_name: ${{ github.head_ref }}
          generate_release_notes: true
          files: release.zip
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
